# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1145, 790)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 771, 731))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(300, 660, 171, 41))
        self.pushButton.setObjectName("pushButton")
        self.image_viewer = QtWidgets.QLabel(self.groupBox)
        self.image_viewer.setGeometry(QtCore.QRect(60, 60, 651, 541))
        self.image_viewer.setAlignment(QtCore.Qt.AlignCenter)
        self.image_viewer.setObjectName("image_viewer")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(810, 10, 321, 731))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1145, 21))
        self.menubar.setObjectName("menubar")
        self.archive_menu = QtWidgets.QMenu(self.menubar)
        self.archive_menu.setObjectName("archive_menu")
        self.filter_menu = QtWidgets.QMenu(self.menubar)
        self.filter_menu.setObjectName("filter_menu")
        MainWindow.setMenuBar(self.menubar)
        self.load_image_menu_option = QtWidgets.QAction(MainWindow)
        self.load_image_menu_option.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.load_image_menu_option.setIconVisibleInMenu(True)
        self.load_image_menu_option.setObjectName("load_image_menu_option")
        self.bilateral_filter_menu_option = QtWidgets.QAction(MainWindow)
        self.bilateral_filter_menu_option.setObjectName("bilateral_filter_menu_option")
        self.anisotropic_filter_menu_option = QtWidgets.QAction(MainWindow)
        self.anisotropic_filter_menu_option.setObjectName("anisotropic_filter_menu_option")
        self.archive_menu.addAction(self.load_image_menu_option)
        self.filter_menu.addAction(self.bilateral_filter_menu_option)
        self.filter_menu.addAction(self.anisotropic_filter_menu_option)
        self.menubar.addAction(self.archive_menu.menuAction())
        self.menubar.addAction(self.filter_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Comparar con original"))
        self.image_viewer.setText(_translate("MainWindow", "TextLabel"))
        self.archive_menu.setTitle(_translate("MainWindow", "Archivo"))
        self.filter_menu.setTitle(_translate("MainWindow", "Filtros"))
        self.load_image_menu_option.setText(_translate("MainWindow", "Cargar imagen"))
        self.bilateral_filter_menu_option.setText(_translate("MainWindow", "Filtro bilateral"))
        self.anisotropic_filter_menu_option.setText(_translate("MainWindow", "Filtro anisotrópico"))
