DOCTOR_DIRECTORY = r""
TEMPORARY_VIDEO_DIRECTORY_PATH = r"./generated/video_frames/"
METRICS_DIRECTORY_PATH = r"./generated/metrics/"
GENERATED_IMAGES_DIR = r"./generated/"
TEST_IMAGES_DIR = r"./Resources/Mediciones"
GENERAL_DIRECTORY = r"./Resources"
TESTS_TEXTURE_DIRECTORY = r"./generated/tests"
TESTS_K_MEAN_TEXTURE_DIRECTORY = r"./generated/tests/k-means"
TESTS_KOHONEN_TEXTURE_DIRECTORY = r"./generated/tests/kohonen"
TESTS_MEAN_SHIFT_TEXTURE_DIRECTORY = r"./generated/tests/mean-shift"
TESTS_HDBSCAN_TEXTURE_DIRECTORY = r"./generated/tests/HDBScan"

