## Keys

# Default image path

IMAGES_SOURCE_FOLDER = "images_source_folder"
OUTPUT_FOLDER = "output_folder"

# Main window properties

# Anisotropic filter

ANISOTROPIC_FILTER_TIMES = "ANISOTROPIC_FILTER"

# Adaptive threshold

ADAPTIVE_THRESHOLD_WINDOW_SIZE = "ADAPTIVE_THRESHOLD_WINDOW_SIZE"
ADAPTIVE_THRESHOLD_C_CONSTANT = "ADAPTIVE_THRESHOLD_C_CONSTANT"
ADAPTIVE_THRESHOLD_METHOD = "ADAPTIVE_THRESHOLD_METHOD"

# MGAC

MGAC_ITERATIONS = "MGAC_ITERATIONS"
MGAC_THRESHOLD = "MGAC_THRESHOLD"
MGAC_SMOOTHING = "MGAC_SMOOTHING"
MGAC_BALLOON = "MGAC_BALLOON"
MGAC_ALPHA = "MGAC_ALPHA"
MGAC_SIGMA = "MGAC_SIGMA"

# Texture

TEXTURE_IMAGE_CLUSTERS = "TEXTURE_IMAGE_CLUSTERS"
TEXTURE_VIDEO_THRESHOLD = "TEXTURE_VIDEO_THRESHOLD"
TEXTURE_VIDEO_CLUSTERS = "TEXTURE_VIDEO_CLUSTERS"

# Movement

TEXTURE_MOVEMENT_THRESHOLD = "TEXTURE_MOVEMENT_THRESHOLD"

# Global routine properties

GLOBAL_ROUTINE_ANISOTROPIC_FILTER_TIMES = "GLOBAL_ROUTINE_ANISOTROPIC_FILTER_TIMES"

GLOBAL_ROUTINE_ADAPTIVE_THRESHOLD_WINDOW_SIZE = "GLOBAL_ROUTINE_ADAPTIVE_THRESHOLD_WINDOW_SIZE"
GLOBAL_ROUTINE_ADAPTIVE_C_CONSTANT = "GLOBAL_ROUTINE_ADAPTIVE_C_CONSTANT"
GLOBAL_ROUTINE_ADAPTIVE_METHOD = "GLOBAL_ROUTINE_ADAPTIVE_METHOD"

GLOBAL_ROUTINE_MGAC_ITERATIONS = "GLOBAL_ROUTINE_MGAC_ITERATIONS"
GLOBAL_ROUTINE_MGAC_THRESHOLD = "GLOBAL_ROUTINE_MGAC_THRESHOLD"
GLOBAL_ROUTINE_MGAC_SMOOTHING = "GLOBAL_ROUTINE_MGAC_SMOOTHING"
GLOBAL_ROUTINE_MGAC_BALLOON = "GLOBAL_ROUTINE_MGAC_BALLOON"
GLOBAL_ROUTINE_MGAC_ALPHA = "GLOBAL_ROUTINE_MGAC_ALPHA"
GLOBAL_ROUTINE_MGAC_SIGMA = "GLOBAL_ROUTINE_MGAC_SIGMA"

GLOBAL_ROUTINE_MOVEMENT_THRESHOLD = "GLOBAL_ROUTINE_MOVEMENT_THRESHOLD"

GLOBAL_ROUTINE_TEXTURE_THRESHOLD = "GLOBAL_ROUTINE_TEXTURE_THRESHOLD"
GLOBAL_ROUTINE_TEXTURE_CLUSTERS = "GLOBAL_ROUTINE_TEXTURE_CLUSTERS"

## Values

# Main window properties

# Anisotropic filter

ANISOTROPIC_FILTER_TIMES_VALUE = 1

# Adaptive threshold

ADAPTIVE_THRESHOLD_WINDOW_SIZE_VALUE = 7
ADAPTIVE_THRESHOLD_C_CONSTANT_VALUE = 3
ADAPTIVE_THRESHOLD_METHOD_VALUE = 1

# MGAC

MGAC_ITERATIONS_VALUE = 220
MGAC_THRESHOLD_VALUE = 0.35
MGAC_SMOOTHING_VALUE = 0
MGAC_BALLOON_VALUE = -1
MGAC_ALPHA_VALUE = 200
MGAC_SIGMA_VALUE = 2

# Texture

TEXTURE_IMAGE_CLUSTERS_VALUE = 10
TEXTURE_VIDEO_THRESHOLD_VALUE = 15
TEXTURE_VIDEO_CLUSTERS_VALUE = 10

# Movement

TEXTURE_MOVEMENT_THRESHOLD_VALUE = 15

# Global routine properties

GLOBAL_ROUTINE_ANISOTROPIC_FILTER_TIMES_VALUE = 1

GLOBAL_ROUTINE_ADAPTIVE_THRESHOLD_WINDOW_SIZE_VALUE = 7
GLOBAL_ROUTINE_ADAPTIVE_C_CONSTANT_VALUE = 6
GLOBAL_ROUTINE_ADAPTIVE_METHOD_VALUE = 1

GLOBAL_ROUTINE_MGAC_ITERATIONS_VALUE = 220
GLOBAL_ROUTINE_MGAC_THRESHOLD_VALUE = 0.35
GLOBAL_ROUTINE_MGAC_SMOOTHING_VALUE = 0
GLOBAL_ROUTINE_MGAC_BALLOON_VALUE = -1
GLOBAL_ROUTINE_MGAC_ALPHA_VALUE = 200
GLOBAL_ROUTINE_MGAC_SIGMA_VALUE = 2

GLOBAL_ROUTINE_MOVEMENT_THRESHOLD_VALUE = 15

GLOBAL_ROUTINE_TEXTURE_THRESHOLD_VALUE = 15
GLOBAL_ROUTINE_TEXTURE_CLUSTERS_VALUE = 10