# Default image path

IMAGES_SOURCE_FOLDER = "images_source_folder"

# Global routine properties

GLOBAL_ROUTINE_ANISOTROPIC_FILTER_TIMES = "GLOBAL_ROUTINE_ANISOTROPIC_FILTER_TIMES"

GLOBAL_ROUTINE_ADAPTIVE_THRESHOLD_WINDOW_SIZE = "GLOBAL_ROUTINE_ADAPTIVE_THRESHOLD_WINDOW_SIZE"
GLOBAL_ROUTINE_ADAPTIVE_C_CONSTANT = "GLOBAL_ROUTINE_ADAPTIVE_C_CONSTANT"
GLOBAL_ROUTINE_ADAPTIVE_METHOD = "GLOBAL_ROUTINE_ADAPTIVE_METHOD"

GLOBAL_ROUTINE_MGAC_ITERATIONS = "GLOBAL_ROUTINE_MGAC_ITERATIONS"
GLOBAL_ROUTINE_MGAC_THRESHOLD = "GLOBAL_ROUTINE_MGAC_THRESHOLD"
GLOBAL_ROUTINE_MGAC_SMOOTHING = "GLOBAL_ROUTINE_MGAC_SMOOTHING"
GLOBAL_ROUTINE_MGAC_BALLOON = "GLOBAL_ROUTINE_MGAC_BALLOON"
GLOBAL_ROUTINE_MGAC_ALPHA = "GLOBAL_ROUTINE_MGAC_ALPHA"
GLOBAL_ROUTINE_MGAC_SIGMA = "GLOBAL_ROUTINE_MGAC_SIGMA"

GLOBAL_ROUTINE_MOVEMENT_THRESHOLD = "GLOBAL_ROUTINE_MOVEMENT_THRESHOLD"

GLOBAL_ROUTINE_TEXTURE_THRESHOLD = "GLOBAL_ROUTINE_TEXTURE_THRESHOLD"
GLOBAL_ROUTINE_TEXTURE_CLUSTERS = "GLOBAL_ROUTINE_TEXTURE_THRESHOLD"

